export interface CityDeliveryInfo {
  name: string
  slug: string
  state: string
  region: "North" | "South" | "West" | "East" | "Central"
  deliveryTime: string
  pinCodesCount: string
  popularAreas: string[]
  tagline: string
  rating: string
  ordersCount: string
  keywords: string[]
}

export const MAJOR_INDIAN_CITIES: CityDeliveryInfo[] = [
  // ==========================================
  // NATIONAL CAPITAL REGION & NORTH INDIA
  // ==========================================
  {
    name: "Delhi NCR",
    slug: "delhi",
    state: "Delhi & NCR",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "140+ PIN Codes",
    popularAreas: ["South Delhi", "Connaught Place", "Dwarka", "Rohini", "Noida", "Gurgaon", "Ghaziabad", "Faridabad", "Vasant Kunj"],
    tagline: "Fastest Express Air & Road Delivery directly from Agra to your Delhi NCR doorstep.",
    rating: "4.9★",
    ordersCount: "18,400+ Orders",
    keywords: ["buy petha delhi", "agra petha delivery delhi", "order petha online delhi", "petha home delivery delhi ncr", "best petha shop delhi"]
  },
  {
    name: "Noida",
    slug: "noida",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["Sector 18", "Sector 62", "Sector 137", "Sector 76", "Noida Expressway", "Sector 50", "Sector 128"],
    tagline: "Same-day dispatched fresh Agra petha & crunchy dalmoth delivered directly to Noida sectors.",
    rating: "4.9★",
    ordersCount: "8,900+ Orders",
    keywords: ["buy petha noida", "agra petha in noida", "order petha online noida", "petha delivery noida", "famous agra petha noida"]
  },
  {
    name: "Greater Noida",
    slug: "greater-noida",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Alpha 1", "Beta 2", "Pari Chowk", "Greater Noida West", "Knowledge Park", "Omega 1", "Gaur City"],
    tagline: "Direct express delivery of pure authentic Agra petha across Greater Noida & Noida Extension.",
    rating: "4.8★",
    ordersCount: "4,300+ Orders",
    keywords: ["buy petha greater noida", "petha delivery greater noida", "agra petha gaur city", "order sweets online greater noida"]
  },
  {
    name: "Gurugram (Gurgaon)",
    slug: "gurgaon",
    state: "Haryana",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "50+ PIN Codes",
    popularAreas: ["Cyber City", "Golf Course Road", "DLF Phase 1-5", "Sohna Road", "MG Road", "Sector 56", "Sector 45"],
    tagline: "Delivering melt-in-mouth Kesar Angoori & Paan Petha fresh to tech parks and homes across Gurgaon.",
    rating: "4.9★",
    ordersCount: "11,200+ Orders",
    keywords: ["buy petha gurgaon", "agra petha in gurgaon", "order petha gurugram", "petha delivery gurgaon", "best petha dlf gurgaon"]
  },
  {
    name: "Ghaziabad",
    slug: "ghaziabad",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Indirapuram", "Vaishali", "Vasundhara", "Raj Nagar Extension", "Crossings Republik", "Kaushambi"],
    tagline: "Fast doorstep courier of authentic GI-heritage Agra sweets across Ghaziabad & Indirapuram.",
    rating: "4.9★",
    ordersCount: "6,800+ Orders",
    keywords: ["buy petha ghaziabad", "agra petha indirapuram", "petha delivery vaishali", "order petha raj nagar ghaziabad"]
  },
  {
    name: "Faridabad",
    slug: "faridabad",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Sector 15", "Sector 21C", "NIT Faridabad", "Neharpar", "Greenfield Colony", "Sector 37"],
    tagline: "Freshly prepared vacuum-packed Agra sweets delivered directly to Faridabad.",
    rating: "4.8★",
    ordersCount: "4,700+ Orders",
    keywords: ["buy petha faridabad", "agra petha delivery faridabad", "order petha nit faridabad", "petha shop faridabad"]
  },
  {
    name: "Kanpur",
    slug: "kanpur",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["Civil Lines", "Swaroop Nagar", "Kakadeo", "Kidwai Nagar", "Govind Nagar", "Shyam Nagar", "Mall Road"],
    tagline: "The legendary taste of Agra Petha and crunchy Dalmoth delivered straight to Kanpur.",
    rating: "4.9★",
    ordersCount: "9,500+ Orders",
    keywords: ["buy petha kanpur", "agra petha in kanpur", "petha delivery kanpur", "order agra sweets kanpur", "famous petha swaroop nagar kanpur"]
  },
  {
    name: "Lucknow",
    slug: "lucknow",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "60+ PIN Codes",
    popularAreas: ["Gomti Nagar", "Hazratganj", "Aliganj", "Indira Nagar", "Mahanagar", "Jankipuram", "Alambagh", "Vibhuti Khand"],
    tagline: "The royal taste of Agra delivered fresh to the City of Nawabs.",
    rating: "4.9★",
    ordersCount: "12,800+ Orders",
    keywords: ["buy petha lucknow", "agra petha in lucknow", "order petha lucknow", "famous petha gomti nagar", "petha delivery hazratganj"]
  },
  {
    name: "Varanasi (Kashi)",
    slug: "varanasi",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Lanka", "Sigra", "Assi Ghat", "Cantt", "Bhelupur", "Shivpur", "Godowlia", "Mahmoorganj"],
    tagline: "Sacred city express delivery of 100% pure vegetarian, preservative-free Agra Petha.",
    rating: "4.9★",
    ordersCount: "7,600+ Orders",
    keywords: ["buy petha varanasi", "agra petha in varanasi", "petha delivery kashi", "order sweets online varanasi"]
  },
  {
    name: "Prayagraj (Allahabad)",
    slug: "prayagraj",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Civil Lines", "George Town", "Tagore Town", "Katra", "Allahpur", "Jhusi", "Naini"],
    tagline: "Authentic Agra sweets and crunchy royal dalmoth air-delivered to Sangam city.",
    rating: "4.9★",
    ordersCount: "6,400+ Orders",
    keywords: ["buy petha prayagraj", "agra petha in allahabad", "petha delivery civil lines prayagraj", "order petha allahabad"]
  },
  {
    name: "Meerut",
    slug: "meerut",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Shastri Nagar", "Saket", "Civil Lines", "Modipuram", "Pallavpuram", "Rohta Road"],
    tagline: "Fresh batch Agra petha delivered directly to your doorstep in Meerut within 24 hours.",
    rating: "4.8★",
    ordersCount: "5,100+ Orders",
    keywords: ["buy petha meerut", "agra petha in meerut", "petha delivery shastri nagar", "order sweets meerut"]
  },
  {
    name: "Bareilly",
    slug: "bareilly",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Civil Lines", "Rajendra Nagar", "Rampur Garden", "DD Puram", "Suresh Sharma Nagar"],
    tagline: "Finest quality authentic Agra petha boxes express shipped to Bareilly.",
    rating: "4.8★",
    ordersCount: "4,100+ Orders",
    keywords: ["buy petha bareilly", "agra petha in bareilly", "petha delivery civil lines bareilly"]
  },
  {
    name: "Aligarh",
    slug: "aligarh",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Centre Point", "Civil Lines", "Marris Road", "Dodhpur", "Ramghat Road"],
    tagline: "Neighbouring Agra city express dispatch: get sweet boxes in record time across Aligarh.",
    rating: "4.9★",
    ordersCount: "5,800+ Orders",
    keywords: ["buy petha aligarh", "agra petha in aligarh", "fresh petha delivery marris road aligarh"]
  },
  {
    name: "Moradabad",
    slug: "moradabad",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Civil Lines", "Mansi Vihar", "Ashiyana", "Ram Ganga Vihar", "Budh Bazaar"],
    tagline: "Handcrafted Agra sweets and traditional dalmoth delivered to the Brass City.",
    rating: "4.8★",
    ordersCount: "3,700+ Orders",
    keywords: ["buy petha moradabad", "agra petha in moradabad", "order petha ram ganga vihar"]
  },
  {
    name: "Gorakhpur",
    slug: "gorakhpur",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Civil Lines", "Golghar", "Medical College Road", "Shahpur", "Taramandal"],
    tagline: "Direct overnight express delivery of fresh Agra petha to Gorakhpur & Eastern UP.",
    rating: "4.8★",
    ordersCount: "4,900+ Orders",
    keywords: ["buy petha gorakhpur", "agra petha in golghar", "petha delivery gorakhpur", "order petha online gorakhpur"]
  },
  {
    name: "Saharanpur",
    slug: "saharanpur",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Court Road", "Delhi Road", "Mission Compound", "Hakikat Nagar", "Janak Nagar"],
    tagline: "Pure authentic Agra petha made with real ash gourd delivered to Saharanpur.",
    rating: "4.8★",
    ordersCount: "3,200+ Orders",
    keywords: ["buy petha saharanpur", "agra petha delivery saharanpur", "sweets shop saharanpur"]
  },
  {
    name: "Jhansi",
    slug: "jhansi",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Sadar Bazaar", "Civil Lines", "Elite Crossing", "Sipri Bazaar", "Nandanpura"],
    tagline: "Authentic royal sweets and savory Dalmoth delivered straight to Bundelkhand hub Jhansi.",
    rating: "4.8★",
    ordersCount: "3,500+ Orders",
    keywords: ["buy petha jhansi", "agra petha in jhansi", "order petha sadar bazaar jhansi"]
  },
  {
    name: "Mathura",
    slug: "mathura",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Vrindavan", "Dampier Nagar", "Krishna Nagar", "Highway City", "Govardhan Road"],
    tagline: "Direct neighbor delivery from Agra: authentic petha dispatched to Mathura & Vrindavan daily.",
    rating: "4.9★",
    ordersCount: "6,200+ Orders",
    keywords: ["buy petha mathura", "agra petha in vrindavan", "petha delivery krishna nagar mathura"]
  },
  {
    name: "Firozabad",
    slug: "firozabad",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "15+ PIN Codes",
    popularAreas: ["Suhag Nagar", "Raja Ka Taal", "SN Road", "Station Road", "Jain Nagar"],
    tagline: "Direct fresh batch dispatch from Agra to the Glass City Firozabad in hours.",
    rating: "4.9★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha firozabad", "fresh agra petha in firozabad", "petha delivery firozabad"]
  },
  {
    name: "Muzaffarnagar",
    slug: "muzaffarnagar",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["New Mandi", "Civil Lines", "Gandhi Colony", "South Civil Lines", "Patel Nagar"],
    tagline: "Freshly vacuum-packed authentic Agra petha boxes delivered to Muzaffarnagar.",
    rating: "4.8★",
    ordersCount: "2,900+ Orders",
    keywords: ["buy petha muzaffarnagar", "agra petha new mandi", "order petha muzaffarnagar"]
  },
  {
    name: "Ayodhya",
    slug: "ayodhya",
    state: "Uttar Pradesh",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Ram Janmabhoomi", "Civil Lines", "Faizabad", "Naya Ghat", "Deokali", "Rikabganj"],
    tagline: "100% pure vegetarian, prasad-grade authentic Agra petha delivered to holy city Ayodhya.",
    rating: "4.9★",
    ordersCount: "5,400+ Orders",
    keywords: ["buy petha ayodhya", "agra petha in ayodhya", "petha delivery ram janmabhoomi", "sweets order ayodhya"]
  },
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "55+ PIN Codes",
    popularAreas: ["Vaishali Nagar", "Malviya Nagar", "C-Scheme", "Mansarovar", "Raja Park", "Tonk Road", "Jagatpura", "Bani Park"],
    tagline: "Direct overnight express delivery from Agra to the Pink City Jaipur.",
    rating: "4.9★",
    ordersCount: "8,300+ Orders",
    keywords: ["buy petha jaipur", "agra petha in jaipur", "order petha online jaipur", "petha delivery c-scheme jaipur", "best petha vaishali nagar"]
  },
  {
    name: "Jodhpur",
    slug: "jodhpur",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Shastri Nagar", "Ratanada", "Sardarpura", "Pal Road", "Paota", "Chopasni Road"],
    tagline: "Delivering royal heritage Agra sweets to the Sun City Jodhpur with guaranteed freshness.",
    rating: "4.9★",
    ordersCount: "4,600+ Orders",
    keywords: ["buy petha jodhpur", "agra petha sardarpura", "order petha online jodhpur", "petha delivery ratanada"]
  },
  {
    name: "Kota",
    slug: "kota",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Vigyan Nagar", "Talwandi", "Dadabari", "Mahaveer Nagar", "Indra Vihar", "Kunhari"],
    tagline: "Delicious energy-rich pure Agra petha boxes delivered to student hubs & families in Kota.",
    rating: "4.9★",
    ordersCount: "5,900+ Orders",
    keywords: ["buy petha kota", "agra petha in talwandi kota", "order petha online indra vihar", "petha delivery vigyan nagar"]
  },
  {
    name: "Bikaner",
    slug: "bikaner",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Rani Bazaar", "Kote Gate", "JNV Colony", "Sadul Ganj", "Pawan Puri"],
    tagline: "From sweet heritage to sweet lovers: authentic Agra petha shipped to Bikaner.",
    rating: "4.8★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha bikaner", "agra petha in bikaner", "order sweets online bikaner"]
  },
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Fatehpura", "Hiran Magri", "Panchwati", "Shobhagpura", "Madhuban", "Sukhadia Circle"],
    tagline: "Royal Agra delicacies air-freighted fresh to the City of Lakes Udaipur.",
    rating: "4.9★",
    ordersCount: "4,800+ Orders",
    keywords: ["buy petha udaipur", "agra petha in udaipur", "order petha hiran magri", "petha delivery fatehpura"]
  },
  {
    name: "Ajmer",
    slug: "ajmer",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Vaishali Nagar", "Civil Lines", "Panchsheel Nagar", "Adarsh Nagar", "Kaisarganj"],
    tagline: "Express door delivery of GI-heritage Agra sweets across Ajmer & Pushkar.",
    rating: "4.8★",
    ordersCount: "3,600+ Orders",
    keywords: ["buy petha ajmer", "agra petha in ajmer", "order petha panchsheel ajmer"]
  },
  {
    name: "Bhilwara",
    slug: "bhilwara",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Subhash Nagar", "Bhopal Ganj", "Shastri Nagar", "Patel Nagar", "Rajendra Marg"],
    tagline: "Fresh traditional Agra sweets dispatched daily to Textile City Bhilwara.",
    rating: "4.8★",
    ordersCount: "2,700+ Orders",
    keywords: ["buy petha bhilwara", "agra petha in bhilwara", "sweets delivery bhilwara"]
  },
  {
    name: "Alwar",
    slug: "alwar",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Manu Marg", "Company Bagh", "MIA Alwar", "Kala Kuan", "Scheme No 2"],
    tagline: "Fast road & express courier delivery from Agra straight to Alwar homes.",
    rating: "4.8★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha alwar", "agra petha in alwar", "order sweets online alwar"]
  },
  {
    name: "Sikar",
    slug: "sikar",
    state: "Rajasthan",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Piprali Road", "Fatehpur Road", "Radhakishan Pura", "Bajaj Gram", "Station Road"],
    tagline: "Authentic Agra petha & spicy Dalmoth delivered to education hub Sikar.",
    rating: "4.8★",
    ordersCount: "2,800+ Orders",
    keywords: ["buy petha sikar", "agra petha piprali road sikar", "order sweets sikar"]
  },
  {
    name: "Chandigarh",
    slug: "chandigarh",
    state: "Punjab & Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["Sector 17", "Sector 35", "Sector 8", "Sector 22", "Sector 9", "Manimajra"],
    tagline: "Freshly packed Agra Petha and Dalmoth for Chandigarh City Beautiful.",
    rating: "4.9★",
    ordersCount: "6,800+ Orders",
    keywords: ["buy petha chandigarh", "agra petha in sector 17", "order petha online chandigarh", "petha delivery sector 35"]
  },
  {
    name: "Mohali",
    slug: "mohali",
    state: "Punjab",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Phase 7", "Phase 3B2", "Phase 5", "Sector 70", "Aerocity", "Kharar"],
    tagline: "Express doorstep delivery of authentic Agra sweets across Mohali & Tricity.",
    rating: "4.8★",
    ordersCount: "4,200+ Orders",
    keywords: ["buy petha mohali", "agra petha in phase 7 mohali", "sweets delivery phase 3b2 mohali"]
  },
  {
    name: "Panchkula",
    slug: "panchkula",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Sector 20", "Sector 4", "Sector 7", "Mansa Devi Complex", "Sector 11", "Sector 15"],
    tagline: "Daily fresh batches of Agra petha shipped directly to Panchkula sectors.",
    rating: "4.8★",
    ordersCount: "3,500+ Orders",
    keywords: ["buy petha panchkula", "agra petha sector 20 panchkula", "order sweets panchkula"]
  },
  {
    name: "Ludhiana",
    slug: "ludhiana",
    state: "Punjab",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["Model Town", "Sarabha Nagar", "Civil Lines", "BRS Nagar", "Ferozepur Road", "Dugri"],
    tagline: "Delivering Punjab's favorite Agra petha & spicy Dalmoth to homes across Ludhiana.",
    rating: "4.9★",
    ordersCount: "6,900+ Orders",
    keywords: ["buy petha ludhiana", "agra petha model town ludhiana", "order petha online sarabha nagar", "petha delivery ludhiana"]
  },
  {
    name: "Amritsar",
    slug: "amritsar",
    state: "Punjab",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Ranjit Avenue", "Mall Road", "Lawrence Road", "Majitha Road", "Civil Lines", "Green Avenue"],
    tagline: "From holy city to holy city: authentic Agra sweets delivered fresh to Amritsar.",
    rating: "4.9★",
    ordersCount: "5,700+ Orders",
    keywords: ["buy petha amritsar", "agra petha lawrence road amritsar", "petha delivery ranjit avenue", "order sweets amritsar"]
  },
  {
    name: "Jalandhar",
    slug: "jalandhar",
    state: "Punjab",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Model Town", "Civil Lines", "Cantt Road", "Urban Estate", "Rama Mandi", "GT Road"],
    tagline: "Crispy savory Dalmoth & royal Agra Petha air-freighted to Jalandhar.",
    rating: "4.8★",
    ordersCount: "4,600+ Orders",
    keywords: ["buy petha jalandhar", "agra petha model town jalandhar", "order sweets online jalandhar"]
  },
  {
    name: "Patiala",
    slug: "patiala",
    state: "Punjab",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Model Town", "Leela Bhawan", "Urban Estate", "Chotti Baradari", "Tripuri"],
    tagline: "Royal Agra petha delivered fresh to the Royal City of Patiala.",
    rating: "4.8★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha patiala", "agra petha leela bhawan patiala", "order sweets patiala"]
  },
  {
    name: "Bathinda",
    slug: "bathinda",
    state: "Punjab",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Civil Lines", "Model Town", "Mall Road", "Guru Nanak Nagar", "Goniana Road"],
    tagline: "Authentic vegetarian Agra sweets delivered safely to Bathinda.",
    rating: "4.8★",
    ordersCount: "2,900+ Orders",
    keywords: ["buy petha bathinda", "agra petha in bathinda", "order petha online bathinda"]
  },
  {
    name: "Panipat",
    slug: "panipat",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Model Town", "Sector 11-12", "GT Road", "Ansals", "Huda Sector 25"],
    tagline: "Fast doorstep courier dispatch of fresh Agra petha to Panipat.",
    rating: "4.8★",
    ordersCount: "3,400+ Orders",
    keywords: ["buy petha panipat", "agra petha model town panipat", "order petha panipat"]
  },
  {
    name: "Ambala",
    slug: "ambala",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Ambala Cantt", "Ambala City", "Model Town", "Prem Nagar", "Cloth Market"],
    tagline: "Direct express delivery of genuine Agra sweets to Ambala Cantt & City.",
    rating: "4.8★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha ambala", "agra petha ambala cantt", "petha delivery ambala city"]
  },
  {
    name: "Karnal",
    slug: "karnal",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Model Town", "Sector 13", "Sector 6", "Sector 14", "Kunjpura Road"],
    tagline: "Freshly packed Agra petha delivered within 24 hours to Karnal.",
    rating: "4.8★",
    ordersCount: "3,600+ Orders",
    keywords: ["buy petha karnal", "agra petha sector 13 karnal", "order petha karnal"]
  },
  {
    name: "Sonipat",
    slug: "sonipat",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Model Town", "Sector 14", "Sector 15", "Omaxe City", "Kundli"],
    tagline: "Rapid doorstep delivery of traditional Agra sweets across Sonipat & Kundli.",
    rating: "4.8★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha sonipat", "agra petha sector 14 sonipat", "petha delivery kundli"]
  },
  {
    name: "Rohtak",
    slug: "rohtak",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Model Town", "Sector 1-4", "Civil Lines", "Delhi Road", "Medical Mor"],
    tagline: "Authentic Agra sweets and crunchy dalmoth delivered to Rohtak.",
    rating: "4.8★",
    ordersCount: "3,200+ Orders",
    keywords: ["buy petha rohtak", "agra petha model town rohtak", "order petha rohtak"]
  },
  {
    name: "Hisar",
    slug: "hisar",
    state: "Haryana",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Model Town", "Urban Estate II", "Sector 14", "Rajguru Market", "PLA Area"],
    tagline: "Preservative-free traditional Agra petha delivered fresh to Hisar.",
    rating: "4.8★",
    ordersCount: "2,800+ Orders",
    keywords: ["buy petha hisar", "agra petha urban estate hisar", "order petha hisar"]
  },
  {
    name: "Dehradun",
    slug: "dehradun",
    state: "Uttarakhand",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Rajpur Road", "Dalanwala", "Vasant Vihar", "Clement Town", "Ballupur", "Jakhan", "Sahastradhara Road"],
    tagline: "Delivering sweet mountain nostalgia: authentic Agra petha air-shipped to Dehradun.",
    rating: "4.9★",
    ordersCount: "5,400+ Orders",
    keywords: ["buy petha dehradun", "agra petha rajpur road dehradun", "order petha online dalanwala", "petha delivery dehradun"]
  },
  {
    name: "Haridwar",
    slug: "haridwar",
    state: "Uttarakhand",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Har Ki Pauri", "Ranipur", "Shivalik Nagar", "Kankhal", "Jwalapur", "BHEL"],
    tagline: "100% pure vegetarian sacred offering grade Agra petha delivered to Haridwar.",
    rating: "4.9★",
    ordersCount: "4,600+ Orders",
    keywords: ["buy petha haridwar", "agra petha kankhal haridwar", "petha delivery har ki pauri", "order sweets haridwar"]
  },
  {
    name: "Rishikesh",
    slug: "rishikesh",
    state: "Uttarakhand",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "15+ PIN Codes",
    popularAreas: ["Tapovan", "Laxman Jhula", "Ram Jhula", "Muni Ki Reti", "AIIMS Rishikesh", "Awas Vikas"],
    tagline: "Fresh pure ash gourd sweet boxes delivered to yoga capital Rishikesh.",
    rating: "4.9★",
    ordersCount: "3,700+ Orders",
    keywords: ["buy petha rishikesh", "agra petha tapovan rishikesh", "order sweets online rishikesh"]
  },
  {
    name: "Roorkee",
    slug: "roorkee",
    state: "Uttarakhand",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "15+ PIN Codes",
    popularAreas: ["IIT Campus", "Civil Lines", "Malviya Chowk", "Ganeshpur", "Roorkee Cantt"],
    tagline: "Express delivery of Agra's finest sweets to IIT Roorkee and city residences.",
    rating: "4.8★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha roorkee", "agra petha iit roorkee", "order petha civil lines roorkee"]
  },
  {
    name: "Haldwani",
    slug: "haldwani",
    state: "Uttarakhand",
    region: "North",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Kathgodam", "Kaladhungi Road", "Nainital Road", "Mukhani", "Tikonia"],
    tagline: "Gateway to Kumaon: fresh Agra petha express delivered to Haldwani & Nainital foothills.",
    rating: "4.8★",
    ordersCount: "3,400+ Orders",
    keywords: ["buy petha haldwani", "agra petha kathgodam", "order sweets haldwani"]
  },
  {
    name: "Shimla",
    slug: "shimla",
    state: "Himachal Pradesh",
    region: "North",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Mall Road", "Sanjauli", "Chotta Shimla", "Kasumpti", "New Shimla", "Jakhu"],
    tagline: "Enjoy authentic warm winter & summer sweets from Agra in the Queen of Hills.",
    rating: "4.9★",
    ordersCount: "3,900+ Orders",
    keywords: ["buy petha shimla", "agra petha mall road shimla", "order sweets online shimla", "petha delivery new shimla"]
  },
  {
    name: "Jammu",
    slug: "jammu",
    state: "Jammu & Kashmir",
    region: "North",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Gandhi Nagar", "Trikuta Nagar", "Channi Himmat", "Bahu Plaza", "Janipur", "Talab Tillo"],
    tagline: "Fresh saffron Kesar Angoori & Paan Petha air-delivered to Jammu City of Temples.",
    rating: "4.8★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha jammu", "agra petha gandhi nagar jammu", "order petha trikuta nagar", "petha delivery jammu"]
  },
  {
    name: "Srinagar",
    slug: "srinagar",
    state: "Jammu & Kashmir",
    region: "North",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Lal Chowk", "Rajbagh", "Hyderpora", "Karan Nagar", "Sanat Nagar", "Bemina"],
    tagline: "Crafted with pure Kashmiri saffron: authentic Agra petha air-freighted to Srinagar.",
    rating: "4.9★",
    ordersCount: "3,200+ Orders",
    keywords: ["buy petha srinagar", "agra petha rajbagh srinagar", "order sweets online srinagar"]
  },

  // ==========================================
  // WEST INDIA (MAHARASHTRA, GUJARAT, GOA)
  // ==========================================
  {
    name: "Mumbai",
    slug: "mumbai",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "120+ PIN Codes",
    popularAreas: ["Bandra", "Andheri", "South Mumbai", "Juhu", "Powai", "Thane", "Navi Mumbai", "Borivali", "Goregaon", "Worli"],
    tagline: "Air-shipped daily from Agra directly to Mumbai with vacuum freshness guarantee.",
    rating: "4.9★",
    ordersCount: "14,200+ Orders",
    keywords: ["buy agra petha mumbai", "fresh petha mumbai", "order petha online mumbai", "petha delivery bandra mumbai", "authentic petha in andheri"]
  },
  {
    name: "Pune",
    slug: "pune",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "75+ PIN Codes",
    popularAreas: ["Kothrud", "Viman Nagar", "Baner", "Wakad", "Hinjewadi", "Aundh", "Kalyani Nagar", "Hadapsar", "Pimpri-Chinchwad"],
    tagline: "Crispy Dalmoth & fresh Kesar Angoori Petha dispatched daily to Pune.",
    rating: "4.9★",
    ordersCount: "8,900+ Orders",
    keywords: ["buy agra petha pune", "order petha pune", "traditional sweets kothrud pune", "petha delivery viman nagar baner"]
  },
  {
    name: "Thane",
    slug: "thane",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Ghodbunder Road", "Majiwada", "Naupada", "Vasant Vihar", "Hiranandani Estate", "Kasarvadavali"],
    tagline: "Air-expressed Agra petha and savory snacks delivered to Thane residences.",
    rating: "4.8★",
    ordersCount: "4,600+ Orders",
    keywords: ["buy petha thane", "agra petha hiranandani estate thane", "petha delivery ghodbunder road", "order sweets thane"]
  },
  {
    name: "Navi Mumbai",
    slug: "navi-mumbai",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Vashi", "Nerul", "Kharghar", "Belapur", "Seawoods", "Airoli", "Panvel"],
    tagline: "Express air-shipped authentic sweet boxes delivered across Navi Mumbai nodes.",
    rating: "4.8★",
    ordersCount: "4,300+ Orders",
    keywords: ["buy petha navi mumbai", "agra petha vashi", "petha delivery kharghar", "order sweets seawoods"]
  },
  {
    name: "Nagpur",
    slug: "nagpur",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["Dharampeth", "Ramdaspeth", "Civil Lines", "Manish Nagar", "Pratap Nagar", "Wardha Road", "Sitabuldi"],
    tagline: "Authentic Agra petha & spicy Dalmoth delivered to the Orange City Nagpur.",
    rating: "4.9★",
    ordersCount: "5,800+ Orders",
    keywords: ["buy petha nagpur", "agra petha dharampeth nagpur", "order petha online nagpur", "petha delivery manish nagar"]
  },
  {
    name: "Nashik",
    slug: "nashik",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["College Road", "Gangapur Road", "Indira Nagar", "Panchavati", "Mahatma Nagar", "Cidco"],
    tagline: "Freshly sealed traditional Agra petha boxes express couriered to Nashik.",
    rating: "4.8★",
    ordersCount: "4,100+ Orders",
    keywords: ["buy petha nashik", "agra petha college road nashik", "petha delivery gangapur road", "order sweets nashik"]
  },
  {
    name: "Chhatrapati Sambhajinagar (Aurangabad)",
    slug: "aurangabad",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["CIDCO", "Samarth Nagar", "Garkheda", "Osmanpura", "Cantonment", "Beed Bypass"],
    tagline: "Heritage meets heritage: authentic Agra sweets delivered to historic Sambhajinagar.",
    rating: "4.8★",
    ordersCount: "3,600+ Orders",
    keywords: ["buy petha aurangabad", "agra petha sambhajinagar", "order sweets cidco aurangabad"]
  },
  {
    name: "Solapur",
    slug: "solapur",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Jule Solapur", "Old Employment", "Saat Rasta", "Ashok Nagar", "Hotgi Road"],
    tagline: "Fresh vacuum-packed Agra petha & spicy Dalmoth delivered to Solapur.",
    rating: "4.8★",
    ordersCount: "2,800+ Orders",
    keywords: ["buy petha solapur", "agra petha in solapur", "order sweets online solapur"]
  },
  {
    name: "Kolhapur",
    slug: "kolhapur",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Rajarampuri", "Tarabai Park", "Nagala Park", "Shahupuri", "Ruikar Colony"],
    tagline: "Sweet balance to Kolhapur flavors: pure authentic Agra petha delivered fresh.",
    rating: "4.9★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha kolhapur", "agra petha rajarampuri", "petha delivery tarabai park kolhapur"]
  },
  {
    name: "Kalyan-Dombivli",
    slug: "kalyan-dombivli",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Kalyan West", "Dombivli East", "Khadakpada", "Palava City", "Tilak Nagar"],
    tagline: "Daily air dispatched sweet boxes delivered to homes in Kalyan & Dombivli.",
    rating: "4.8★",
    ordersCount: "3,700+ Orders",
    keywords: ["buy petha kalyan", "agra petha dombivli east", "petha delivery khadakpada palava"]
  },
  {
    name: "Vasai-Virar",
    slug: "vasai-virar",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Vasai West", "Virar West", "Evershine City", "Yashwant Nagar", "Bolinj"],
    tagline: "Express air cargo sweet boxes delivered across Vasai-Virar region.",
    rating: "4.8★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha vasai", "agra petha virar west", "sweets delivery vasai virar"]
  },
  {
    name: "Pimpri-Chinchwad",
    slug: "pimpri-chinchwad",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–36 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Pimple Saudagar", "Wakad", "Rahatani", "Nigdi", "Chinchwad Station", "Ravet"],
    tagline: "Fresh Agra Petha delivered directly to PCMC tech hubs and residential areas.",
    rating: "4.9★",
    ordersCount: "4,400+ Orders",
    keywords: ["buy petha pimpri chinchwad", "agra petha pimple saudagar", "petha delivery wakad nigdi"]
  },
  {
    name: "Amravati",
    slug: "amravati",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Camp Area", "Rukmini Nagar", "Gadge Nagar", "Rathi Nagar", "Badnera Road"],
    tagline: "Authentic Agra petha and savory Dalmoth delivered to Amravati.",
    rating: "4.8★",
    ordersCount: "2,400+ Orders",
    keywords: ["buy petha amravati", "agra petha in amravati", "order sweets online amravati"]
  },
  {
    name: "Nanded",
    slug: "nanded",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Anand Nagar", "Taroda Naka", "Vazirabad", "Sneha Nagar", "Workshop Road"],
    tagline: "Pure vegetarian Agra sweets delivered to holy city Nanded.",
    rating: "4.8★",
    ordersCount: "2,200+ Orders",
    keywords: ["buy petha nanded", "agra petha in nanded", "sweets delivery nanded"]
  },
  {
    name: "Jalgaon",
    slug: "jalgaon",
    state: "Maharashtra",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Ring Road", "Muktainagar", "Adarsh Nagar", "Mahabal", "Jilha Peth"],
    tagline: "Freshly packed Agra delicacies couriered to Jalgaon.",
    rating: "4.8★",
    ordersCount: "2,300+ Orders",
    keywords: ["buy petha jalgaon", "agra petha in jalgaon", "order sweets jalgaon"]
  },
  {
    name: "Ahmedabad",
    slug: "ahmedabad",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "65+ PIN Codes",
    popularAreas: ["SG Highway", "Satellite", "Bodakdev", "Navrangpura", "Maninagar", "Prahlad Nagar", "Vastrapur", "Thaltej", "Sindhu Bhavan"],
    tagline: "100% pure vegetarian, preservative-free Agra Petha and crunchy Dalmoth for Ahmedabad.",
    rating: "4.9★",
    ordersCount: "7,800+ Orders",
    keywords: ["buy petha ahmedabad", "fresh namkeen ahmedabad", "agra petha delivery satellite ahmedabad", "order petha sg highway", "best petha shop ahmedabad"]
  },
  {
    name: "Surat",
    slug: "surat",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "50+ PIN Codes",
    popularAreas: ["Adajan", "Vesu", "Piplod", "Ghopad", "Varachha", "City Light", "Katargam", "Pal"],
    tagline: "For Surat food lovers: authentic GI-heritage Agra Petha air-delivered fresh.",
    rating: "4.9★",
    ordersCount: "7,100+ Orders",
    keywords: ["buy petha surat", "agra petha adajan surat", "order petha vesu surat", "petha delivery city light surat"]
  },
  {
    name: "Vadodara (Baroda)",
    slug: "vadodara",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["Alkapuri", "Akota", "Gotri", "Manjalpur", "Vasna Road", "Karelibaug", "Fatehgunj"],
    tagline: "The royal sweetness of Agra delivered to the cultural capital of Gujarat.",
    rating: "4.9★",
    ordersCount: "5,300+ Orders",
    keywords: ["buy petha vadodara", "agra petha alkapuri vadodara", "order petha online baroda", "petha delivery gotri vadodara"]
  },
  {
    name: "Rajkot",
    slug: "rajkot",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Kalawad Road", "University Road", "Yagnik Road", "Amin Marg", "Nana Mava", "150 Feet Ring Road"],
    tagline: "Pure vegetarian sweet treats and spiced dalmoth delivered directly to Rajkot.",
    rating: "4.9★",
    ordersCount: "4,600+ Orders",
    keywords: ["buy petha rajkot", "agra petha kalawad road rajkot", "order petha online rajkot", "petha delivery yagnik road"]
  },
  {
    name: "Bhavnagar",
    slug: "bhavnagar",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Kaliyabid", "Waghawadi Road", "Ghogha Circle", "Subhashnagar", "Sardarnagar"],
    tagline: "Handcrafted Agra sweets delivered fresh to Bhavnagar.",
    rating: "4.8★",
    ordersCount: "2,800+ Orders",
    keywords: ["buy petha bhavnagar", "agra petha waghawadi road", "order sweets bhavnagar"]
  },
  {
    name: "Jamnagar",
    slug: "jamnagar",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Patel Colony", "Digvijay Plot", "Park Colony", "Sumair Club Road", "Gulabnagar"],
    tagline: "Express courier delivery of authentic Agra petha boxes to Jamnagar.",
    rating: "4.8★",
    ordersCount: "2,700+ Orders",
    keywords: ["buy petha jamnagar", "agra petha patel colony jamnagar", "order sweets online jamnagar"]
  },
  {
    name: "Gandhinagar",
    slug: "gandhinagar",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Sector 11", "Sector 21", "Infocity", "Kudasan", "Raysan", "GIFT City", "Sargasan"],
    tagline: "Daily fresh sweet shipments to GIFT City, Infocity, and residential sectors of Gandhinagar.",
    rating: "4.9★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha gandhinagar", "agra petha gift city", "order petha infocity gandhinagar", "petha delivery kudasan"]
  },
  {
    name: "Junagadh",
    slug: "junagadh",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Zanzarda Road", "Moti Baug", "Talav Gate", "Joshipura", "College Road"],
    tagline: "Pure authentic Agra petha safely couriered to Junagadh.",
    rating: "4.8★",
    ordersCount: "2,100+ Orders",
    keywords: ["buy petha junagadh", "agra petha in junagadh", "order sweets junagadh"]
  },
  {
    name: "Anand",
    slug: "anand",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Vallabh Vidyanagar", "Amul Dairy Road", "Bakrol", "Mota Bazaar", "Nana Bazaar"],
    tagline: "Fresh royal petha delivered to Milk Capital Anand & Vidyanagar student campuses.",
    rating: "4.9★",
    ordersCount: "3,200+ Orders",
    keywords: ["buy petha anand", "agra petha vallabh vidyanagar", "order sweets online anand"]
  },
  {
    name: "Navsari",
    slug: "navsari",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "15+ PIN Codes",
    popularAreas: ["Lunsikui", "Fuwara", "Station Road", "Jalalpor", "Vijalpore"],
    tagline: "Authentic Agra petha dispatched to Navsari homes.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha navsari", "agra petha in navsari", "sweets delivery navsari"]
  },
  {
    name: "Vapi",
    slug: "vapi",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["GIDC Vapi", "Chala", "Gunjan", "Koparli Road", "Daman Road"],
    tagline: "Express delivery of Agra sweets to industrial and residential Vapi.",
    rating: "4.8★",
    ordersCount: "2,600+ Orders",
    keywords: ["buy petha vapi", "agra petha chala vapi", "order sweets vapi"]
  },
  {
    name: "Bharuch",
    slug: "bharuch",
    state: "Gujarat",
    region: "West",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Zadeshwar Road", "Link Road", "Station Road", "GNFC Township", "Bholav"],
    tagline: "Vacuum freshness guaranteed Agra petha boxes delivered to Bharuch.",
    rating: "4.8★",
    ordersCount: "2,200+ Orders",
    keywords: ["buy petha bharuch", "agra petha zadeshwar bharuch", "order sweets bharuch"]
  },
  {
    name: "Panaji (Goa)",
    slug: "panaji",
    state: "Goa",
    region: "West",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Miramar", "Dona Paula", "Fontainhas", "Caranzalem", "Altinho", "Porvorim"],
    tagline: "Authentic North Indian royal petha air-freighted fresh to Goa.",
    rating: "4.9★",
    ordersCount: "3,400+ Orders",
    keywords: ["buy petha goa", "agra petha panaji goa", "petha delivery porvorim", "order sweets online goa"]
  },
  {
    name: "Margao (Goa)",
    slug: "margao",
    state: "Goa",
    region: "West",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Fatorda", "Borda", "Aquem", "Comba", "Gogol", "Navelim"],
    tagline: "Freshly sealed Agra sweet boxes air-shipped to South Goa hub Margao.",
    rating: "4.8★",
    ordersCount: "2,400+ Orders",
    keywords: ["buy petha margao", "agra petha in south goa", "order sweets fatorda margao"]
  },

  // ==========================================
  // SOUTH INDIA (KARNATAKA, TAMIL NADU, TELANGANA, ANDHRA PRADESH, KERALA)
  // ==========================================
  {
    name: "Bangalore (Bengaluru)",
    slug: "bangalore",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "95+ PIN Codes",
    popularAreas: ["Indiranagar", "Koramangala", "Whitefield", "HSR Layout", "JP Nagar", "Electronic City", "Malleshwaram", "Jayanagar", "Hebbal", "Bellandur"],
    tagline: "Melt-in-mouth royal Agra petha delivered fresh to tech parks and homes across Bengaluru.",
    rating: "4.9★",
    ordersCount: "13,400+ Orders",
    keywords: ["buy petha bangalore", "agra petha online bangalore", "petha delivery koramangala", "petha delivery whitefield hsr", "order agra petha in bangalore"]
  },
  {
    name: "Mysore (Mysuru)",
    slug: "mysore",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Gokulam", "Jayalakshmipuram", "Kuvempunagar", "Saraswathipuram", "Hebbal", "Vijayanagar"],
    tagline: "From Palace City Agra to Heritage City Mysuru: authentic sweet boxes air-delivered.",
    rating: "4.9★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha mysore", "agra petha in gokulam mysuru", "petha delivery kuvempunagar", "order sweets mysore"]
  },
  {
    name: "Hubli-Dharwad",
    slug: "hubli-dharwad",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Vidyanagar", "Keshwapur", "Gokul Road", "Navanagar", "Line Bazaar", "Kallur"],
    tagline: "Freshly prepared Agra petha & spicy Dalmoth delivered to North Karnataka hub.",
    rating: "4.8★",
    ordersCount: "2,900+ Orders",
    keywords: ["buy petha hubli", "agra petha in dharwad", "order petha vidyanagar hubli"]
  },
  {
    name: "Mangalore (Mangaluru)",
    slug: "mangalore",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Kadri", "Kodialbail", "Bejai", "Lalbagh", "Surathkal", "Urwa", "Valencia"],
    tagline: "Air-freighted sealed fresh Agra delicacies delivered along Coastal Karnataka.",
    rating: "4.9★",
    ordersCount: "3,400+ Orders",
    keywords: ["buy petha mangalore", "agra petha kadri mangaluru", "order sweets surathkal mangalore"]
  },
  {
    name: "Belgaum (Belagavi)",
    slug: "belgaum",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Tilakwadi", "Camp", "Hindwadi", "Khanapur Road", "Udyambag", "Channamma Circle"],
    tagline: "Authentic North Indian petha & Dalmoth delivered to Belagavi residences.",
    rating: "4.8★",
    ordersCount: "2,600+ Orders",
    keywords: ["buy petha belgaum", "agra petha tilakwadi belagavi", "order sweets belgaum"]
  },
  {
    name: "Davanagere",
    slug: "davanagere",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["MCC B Block", "Vidyanagar", "KB Extension", "Hadadi Road", "PJ Extension"],
    tagline: "Pure vegetarian Agra petha delivered fresh to Davanagere.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha davanagere", "agra petha in davanagere", "sweets delivery davanagere"]
  },
  {
    name: "Bellary (Ballari)",
    slug: "bellary",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Gandhinagar", "Cantonment", "Infantry Road", "Patel Nagar", "Cowal Bazaar"],
    tagline: "Delicious Agra petha boxes express couriered to Ballari.",
    rating: "4.8★",
    ordersCount: "1,800+ Orders",
    keywords: ["buy petha bellary", "agra petha ballari", "order sweets bellary"]
  },
  {
    name: "Gulbarga (Kalaburagi)",
    slug: "gulbarga",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Aiwan-e-Shahi", "Sedam Road", "Brahampur", "Super Market", "Maktampura"],
    tagline: "Authentic GI-heritage Agra sweets delivered to Kalaburagi.",
    rating: "4.8★",
    ordersCount: "1,700+ Orders",
    keywords: ["buy petha gulbarga", "agra petha kalaburagi", "order sweets online gulbarga"]
  },
  {
    name: "Shimoga (Shivamogga)",
    slug: "shimoga",
    state: "Karnataka",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Gopala", "Vinoba Nagara", "Jayanagara", "Durgigudi", "Vidyanagara"],
    tagline: "Fresh Agra sweet boxes delivered to the Malnad hub of Shivamogga.",
    rating: "4.8★",
    ordersCount: "1,800+ Orders",
    keywords: ["buy petha shimoga", "agra petha shivamogga", "order sweets vinoba nagara"]
  },
  {
    name: "Hyderabad",
    slug: "hyderabad",
    state: "Telangana",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "85+ PIN Codes",
    popularAreas: ["Banjara Hills", "Jubilee Hills", "Hitech City", "Gachibowli", "Secunderabad", "Madhapur", "Kukatpally", "Kondapur", "Begumpet", "Manikonda"],
    tagline: "Authentic royal Agra sweets and spiced Dalmoth delivered across the City of Pearls.",
    rating: "4.9★",
    ordersCount: "10,900+ Orders",
    keywords: ["buy petha hyderabad", "order petha online hyderabad", "agra sweets delivery gachibowli", "petha sweet shop banjara hills", "fresh petha hitech city"]
  },
  {
    name: "Warangal",
    slug: "warangal",
    state: "Telangana",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Hanamkonda", "Kazipet", "Subedari", "Nakkalagutta", "Kakatiya University", "Balanagar"],
    tagline: "Express air-shipped authentic Agra petha boxes delivered to Warangal-Hanamkonda.",
    rating: "4.8★",
    ordersCount: "2,700+ Orders",
    keywords: ["buy petha warangal", "agra petha hanamkonda", "petha delivery kazipet", "order sweets warangal"]
  },
  {
    name: "Nizamabad",
    slug: "nizamabad",
    state: "Telangana",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Khaleelwadi", "Dubba", "Subhashnagar", "Kanteshwar", "Bodhan Road"],
    tagline: "Fresh vacuum-packed Agra sweets delivered to Nizamabad.",
    rating: "4.8★",
    ordersCount: "1,800+ Orders",
    keywords: ["buy petha nizamabad", "agra petha in nizamabad", "order sweets nizamabad"]
  },
  {
    name: "Karimnagar",
    slug: "karimnagar",
    state: "Telangana",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Collectorate", "Mukarampura", "Kothirampur", "Vidyanagar", "Mankammathota"],
    tagline: "Authentic North Indian Agra petha delivered directly to Karimnagar.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha karimnagar", "agra petha in karimnagar", "sweets delivery karimnagar"]
  },
  {
    name: "Visakhapatnam (Vizag)",
    slug: "visakhapatnam",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "50+ PIN Codes",
    popularAreas: ["MVP Colony", "Siripuram", "Seethammadhara", "Gajuwaka", "Madhurawada", "Dwaraka Nagar", "Beach Road", "Rushikonda"],
    tagline: "Air-freighted daily from Agra to the City of Destiny Vizag with vacuum sealed freshness.",
    rating: "4.9★",
    ordersCount: "5,400+ Orders",
    keywords: ["buy petha vizag", "agra petha mvp colony vizag", "order petha online visakhapatnam", "petha delivery madhurawada"]
  },
  {
    name: "Vijayawada",
    slug: "vijayawada",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["Benz Circle", "Governorpet", "Moghalrajpuram", "Labbipet", "Bhavanipuram", "Patamata", "Gunadala"],
    tagline: "Fresh authentic Agra petha and crunchy dalmoth delivered to Vijayawada.",
    rating: "4.9★",
    ordersCount: "4,800+ Orders",
    keywords: ["buy petha vijayawada", "agra petha benz circle", "order sweets online vijayawada", "petha delivery labbipet"]
  },
  {
    name: "Guntur",
    slug: "guntur",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Brodipet", "Arundelpet", "Lakshmipuram", "Vidya Nagar", "Pattabhipuram", "Koretipadu"],
    tagline: "The perfect sweet counterpoint: pure Agra petha delivered fresh to Guntur.",
    rating: "4.8★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha guntur", "agra petha brodipet guntur", "order petha arundelpet", "sweets delivery guntur"]
  },
  {
    name: "Nellore",
    slug: "nellore",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Magunta Layout", "Vedayapalem", "Trunk Road", "Pogathota", "Balaji Nagar"],
    tagline: "Express air cargo sweet boxes delivered across Nellore.",
    rating: "4.8★",
    ordersCount: "2,500+ Orders",
    keywords: ["buy petha nellore", "agra petha magunta layout nellore", "order sweets online nellore"]
  },
  {
    name: "Kurnool",
    slug: "kurnool",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["NR Peta", "Santosh Nagar", "Gayatri Estate", "Joharapuram", "Budhawarpet"],
    tagline: "Traditional Agra sweets and crunchy royal dalmoth couriered to Kurnool.",
    rating: "4.8★",
    ordersCount: "2,200+ Orders",
    keywords: ["buy petha kurnool", "agra petha in kurnool", "order sweets kurnool"]
  },
  {
    name: "Rajahmundry",
    slug: "rajahmundry",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Danavaipeta", "Innespeta", "Aryapuram", "Prakash Nagar", "Tilak Road"],
    tagline: "Pure authentic Agra petha air-expressed to the banks of Godavari in Rajahmundry.",
    rating: "4.8★",
    ordersCount: "2,600+ Orders",
    keywords: ["buy petha rajahmundry", "agra petha in rajahmundry", "order sweets danavaipeta"]
  },
  {
    name: "Tirupati",
    slug: "tirupati",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Alipiri", "Bhavani Nagar", "Korlagunta", "AIR Bypass Road", "MR Palli", "Chandragiri"],
    tagline: "100% pure vegetarian sacred grade sweet boxes delivered to pilgrims and residents in Tirupati.",
    rating: "4.9★",
    ordersCount: "4,100+ Orders",
    keywords: ["buy petha tirupati", "agra petha in tirupati", "order sweets alipiri tirupati", "petha delivery tirupati"]
  },
  {
    name: "Kakinada",
    slug: "kakinada",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Suryaraopeta", "Gandhi Nagar", "Bhanugudi Junction", "Madhavapatnam", "Gaigolupadu"],
    tagline: "Fresh sealed Agra petha boxes air-freighted to Smart City Kakinada.",
    rating: "4.8★",
    ordersCount: "2,300+ Orders",
    keywords: ["buy petha kakinada", "agra petha in kakinada", "order sweets online kakinada"]
  },
  {
    name: "Anantapur",
    slug: "anantapur",
    state: "Andhra Pradesh",
    region: "South",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Housing Board Colony", "Subash Nagar", "Rudrampeta", "Court Road", "Kamalanagar"],
    tagline: "Authentic Agra sweets safely dispatched to Anantapur.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha anantapur", "agra petha in anantapur", "order sweets anantapur"]
  },
  {
    name: "Chennai",
    slug: "chennai",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "70+ PIN Codes",
    popularAreas: ["Anna Nagar", "T. Nagar", "Adyar", "Velachery", "Mylapore", "Nungambakkam", "OMR", "Besant Nagar", "Kilpauk"],
    tagline: "Authentic North Indian heritage sweet boxes safely air-freighted to Chennai.",
    rating: "4.9★",
    ordersCount: "7,300+ Orders",
    keywords: ["buy petha online chennai", "agra sweets t nagar chennai", "petha delivery anna nagar", "order agra petha adyar chennai", "best petha shop chennai"]
  },
  {
    name: "Coimbatore",
    slug: "coimbatore",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["RS Puram", "Gandhipuram", "Peelamedu", "Saibaba Colony", "Race Course", "Saravanampatti", "Singanallur"],
    tagline: "Air-freighted fresh Agra petha & spicy Dalmoth delivered to Manchester of South India.",
    rating: "4.9★",
    ordersCount: "4,600+ Orders",
    keywords: ["buy petha coimbatore", "agra petha rs puram coimbatore", "order petha gandhipuram", "petha delivery peelamedu"]
  },
  {
    name: "Madurai",
    slug: "madurai",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["KK Nagar", "Anna Nagar", "Simmakkal", "SS Colony", "TVS Nagar", "Mattuthavani"],
    tagline: "Pure authentic Agra petha air-expressed to the Temple City Madurai.",
    rating: "4.8★",
    ordersCount: "3,400+ Orders",
    keywords: ["buy petha madurai", "agra petha kk nagar madurai", "petha delivery anna nagar madurai"]
  },
  {
    name: "Tiruchirappalli (Trichy)",
    slug: "trichy",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Thillai Nagar", "Cantonment", "K.K. Nagar", "Srirangam", "TVS Tollgate", "Palakarai"],
    tagline: "Delivering vacuum-sealed Agra sweets directly to Trichy & Srirangam.",
    rating: "4.8★",
    ordersCount: "2,800+ Orders",
    keywords: ["buy petha trichy", "agra petha thillai nagar trichy", "order sweets srirangam"]
  },
  {
    name: "Salem",
    slug: "salem",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Fairlands", "Hasthampatti", "Alagapuram", "Suramangalam", "Ammapet", "Shevapet"],
    tagline: "Fresh Agra delicacies air-expressed to Salem residences.",
    rating: "4.8★",
    ordersCount: "2,600+ Orders",
    keywords: ["buy petha salem", "agra petha fairlands salem", "order sweets online salem"]
  },
  {
    name: "Tiruppur",
    slug: "tiruppur",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Avinashi Road", "Kangeyam Road", "Palladam Road", "Kumar Nagar", "Gandhi Nagar"],
    tagline: "Authentic Agra petha delivered to the textile hub of Tiruppur.",
    rating: "4.8★",
    ordersCount: "2,400+ Orders",
    keywords: ["buy petha tiruppur", "agra petha avinashi road", "order sweets tiruppur"]
  },
  {
    name: "Erode",
    slug: "erode",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Perundurai Road", "Surampatti", "Veerappanchatram", "Brough Road", "Thindal"],
    tagline: "Air-expressed fresh sweet boxes delivered to Turmeric City Erode.",
    rating: "4.8★",
    ordersCount: "2,100+ Orders",
    keywords: ["buy petha erode", "agra petha in erode", "order sweets thindal erode"]
  },
  {
    name: "Vellore",
    slug: "vellore",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Gandhinagar", "Katpadi", "Sathuvachari", "CMC Campus", "Bagayam", "VIT Campus"],
    tagline: "Express delivery of Agra sweets to VIT, CMC students and families in Vellore.",
    rating: "4.9★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha vellore", "agra petha vit campus vellore", "order sweets katpadi vellore"]
  },
  {
    name: "Thoothukudi (Tuticorin)",
    slug: "thoothukudi",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Millerpuram", "Chidambara Nagar", "Cruzpuram", "Bryant Nagar", "Muthammal Colony"],
    tagline: "Authentic North Indian Agra petha air-freighted to Pearl City Thoothukudi.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha thoothukudi", "agra petha tuticorin", "order sweets online thoothukudi"]
  },
  {
    name: "Thanjavur",
    slug: "thanjavur",
    state: "Tamil Nadu",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Medical College Road", "Yagappa Nagar", "Rahman Nagar", "Old Bus Stand", "Nanjikottai"],
    tagline: "Traditional Agra sweets delivered to historic cultural hub Thanjavur.",
    rating: "4.8★",
    ordersCount: "1,800+ Orders",
    keywords: ["buy petha thanjavur", "agra petha in thanjavur", "order sweets thanjavur"]
  },
  {
    name: "Kochi (Cochin)",
    slug: "kochi",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "50+ PIN Codes",
    popularAreas: ["Kakkanad", "Kaloor", "Panampilly Nagar", "Edappally", "Fort Kochi", "Aluva", "MG Road", "Marine Drive"],
    tagline: "Authentic North Indian petha and Dalmoth express air-delivered to Queen of Arabian Sea.",
    rating: "4.9★",
    ordersCount: "4,900+ Orders",
    keywords: ["buy petha kochi", "agra petha panampilly nagar kochi", "order sweets kakkanad cochin", "petha delivery edappally"]
  },
  {
    name: "Thiruvananthapuram (Trivandrum)",
    slug: "trivandrum",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["Kowdiar", "Vellayambalam", "Pattom", "Technopark", "Kazhakkoottam", "Sasthamangalam", "Statue"],
    tagline: "Air-freighted fresh Agra petha delivered to Kerala's capital and Technopark techies.",
    rating: "4.9★",
    ordersCount: "4,200+ Orders",
    keywords: ["buy petha trivandrum", "agra petha technopark trivandrum", "order petha kowdiar", "petha delivery thiruvananthapuram"]
  },
  {
    name: "Kozhikode (Calicut)",
    slug: "calicut",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Mavoor Road", "Beach Road", "Thondayad", "Chevayur", "Palayam", "Nadakkavu"],
    tagline: "For Calicut food connoisseurs: authentic Agra petha air-freighted fresh.",
    rating: "4.9★",
    ordersCount: "3,600+ Orders",
    keywords: ["buy petha calicut", "agra petha kozhikode", "order sweets online calicut", "petha delivery mavoor road"]
  },
  {
    name: "Thrissur",
    slug: "thrissur",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Round West", "Swaraj Round", "Ayyanthole", "Chembukkavu", "Olarikkara", "Kuriachira"],
    tagline: "Pure vegetarian Agra sweets delivered to Kerala's cultural capital Thrissur.",
    rating: "4.8★",
    ordersCount: "2,700+ Orders",
    keywords: ["buy petha thrissur", "agra petha in thrissur", "order sweets online thrissur"]
  },
  {
    name: "Kollam (Quilon)",
    slug: "kollam",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Asramam", "Chinnakada", "Kadappakada", "Kavanad", "Thirumullavaram"],
    tagline: "Freshly sealed traditional Agra petha boxes air-shipped to Kollam.",
    rating: "4.8★",
    ordersCount: "2,100+ Orders",
    keywords: ["buy petha kollam", "agra petha in quilon", "sweets delivery kollam"]
  },
  {
    name: "Kannur",
    slug: "kannur",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Thavakkara", "Payyambalam", "Talap", "South Bazaar", "Puzhathi"],
    tagline: "Authentic Agra petha & spicy Dalmoth couriered to Kannur.",
    rating: "4.8★",
    ordersCount: "2,000+ Orders",
    keywords: ["buy petha kannur", "agra petha in kannur", "order sweets kannur"]
  },
  {
    name: "Alappuzha (Alleppey)",
    slug: "alappuzha",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Mullakkal", "Civil Station", "Thathampally", "Punnamada", "Kalarcode"],
    tagline: "Delivering sweet royalty from Agra across the backwaters of Alleppey.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha alappuzha", "agra petha alleppey", "order sweets online alappuzha"]
  },
  {
    name: "Palakkad",
    slug: "palakkad",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Sultanpet", "Chandranagar", "Kalpathy", "Pirayiri", "Civil Station"],
    tagline: "Vacuum freshness guaranteed Agra petha boxes delivered to Palakkad.",
    rating: "4.8★",
    ordersCount: "1,800+ Orders",
    keywords: ["buy petha palakkad", "agra petha in palakkad", "order sweets palakkad"]
  },
  {
    name: "Kottayam",
    slug: "kottayam",
    state: "Kerala",
    region: "South",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Collectorate", "Kanjikuzhy", "Nagampadam", "Kumaranalloor", "Nattakom"],
    tagline: "Authentic Agra sweets delivered fresh to the Land of Letters Kottayam.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha kottayam", "agra petha kanjikuzhy kottayam", "sweets delivery kottayam"]
  },

  // ==========================================
  // CENTRAL INDIA (MADHYA PRADESH & CHHATTISGARH)
  // ==========================================
  {
    name: "Indore",
    slug: "indore",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "50+ PIN Codes",
    popularAreas: ["Vijay Nagar", "Palasia", "Saket", "Geeta Bhawan", "AB Road", "Rajendra Nagar", "Bhawarkua", "Mahalaxmi Nagar"],
    tagline: "For India's street food capital: authentic heritage petha delivered fresh from Agra.",
    rating: "4.9★",
    ordersCount: "6,900+ Orders",
    keywords: ["buy petha indore", "agra petha vijay nagar indore", "order petha online palasia", "petha delivery indore", "best petha shop indore"]
  },
  {
    name: "Bhopal",
    slug: "bhopal",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["MP Nagar", "Arera Colony", "Kolar Road", "Shahpura", "Hoshangabad Road", "Chunabhatti", "Bittan Market"],
    tagline: "Direct express delivery of pure vegetarian Agra petha & Dalmoth across Bhopal.",
    rating: "4.9★",
    ordersCount: "5,800+ Orders",
    keywords: ["buy petha bhopal", "agra petha arera colony bhopal", "order petha mp nagar", "petha delivery kolar road bhopal"]
  },
  {
    name: "Gwalior",
    slug: "gwalior",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "Same Day / 24 Hours",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["City Centre", "Lashkar", "Morar", "Thatipur", "Phoolbagh", "Govindpuri"],
    tagline: "Close neighbor express delivery: daily fresh batches from Agra to Gwalior in hours.",
    rating: "4.9★",
    ordersCount: "6,300+ Orders",
    keywords: ["buy petha gwalior", "agra petha city centre gwalior", "petha delivery lashkar", "order agra petha gwalior"]
  },
  {
    name: "Jabalpur",
    slug: "jabalpur",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Civil Lines", "Wright Town", "Napier Town", "Vijay Nagar", "Gorakhpur Jabalpur", "Madan Mahal"],
    tagline: "Delivering marble freshness: authentic Agra petha express shipped to Jabalpur.",
    rating: "4.8★",
    ordersCount: "4,100+ Orders",
    keywords: ["buy petha jabalpur", "agra petha wright town jabalpur", "order petha online jabalpur"]
  },
  {
    name: "Ujjain",
    slug: "ujjain",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Freeganj", "Mahakal Mandir Area", "Nanaji Deshmukh Nagar", "Sethis Nagar", "Dewas Road"],
    tagline: "100% pure ash gourd prasadam grade Agra petha delivered to holy city Ujjain.",
    rating: "4.9★",
    ordersCount: "4,200+ Orders",
    keywords: ["buy petha ujjain", "agra petha freeganj ujjain", "order sweets mahakal mandir ujjain"]
  },
  {
    name: "Sagar",
    slug: "sagar",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Civil Lines", "Gopal Ganj", "Makronia", "Tili", "Cantt Area"],
    tagline: "Authentic Agra sweets and crunchy dalmoth delivered to Sagar.",
    rating: "4.8★",
    ordersCount: "2,300+ Orders",
    keywords: ["buy petha sagar", "agra petha makronia sagar", "order sweets online sagar"]
  },
  {
    name: "Ratlam",
    slug: "ratlam",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Do Batti", "Station Road", "Alkapuri", "Kasturba Nagar", "Shastri Nagar"],
    tagline: "Sweet pair for Ratlami Sev: authentic GI-heritage Agra petha delivered fresh.",
    rating: "4.9★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha ratlam", "agra petha in ratlam", "order sweets do batti ratlam"]
  },
  {
    name: "Rewa",
    slug: "rewa",
    state: "Madhya Pradesh",
    region: "Central",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Civil Lines", "Bodabag", "Nehru Nagar", "University Road", "Ratahara"],
    tagline: "Fresh vacuum-packed Agra petha boxes delivered to Rewa.",
    rating: "4.8★",
    ordersCount: "2,200+ Orders",
    keywords: ["buy petha rewa", "agra petha in rewa", "order sweets online rewa"]
  },
  {
    name: "Raipur",
    slug: "raipur",
    state: "Chhattisgarh",
    region: "Central",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["Shankar Nagar", "Pandri", "Samta Colony", "Devendra Nagar", "Civil Lines", "VIP Road", "Naya Raipur"],
    tagline: "Air-freighted fresh Agra petha & spicy Dalmoth delivered to Chhattisgarh capital.",
    rating: "4.9★",
    ordersCount: "4,700+ Orders",
    keywords: ["buy petha raipur", "agra petha shankar nagar raipur", "order petha online pandri", "petha delivery devendra nagar"]
  },
  {
    name: "Bhilai",
    slug: "bhilai",
    state: "Chhattisgarh",
    region: "Central",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Sector 6", "Sector 10", "Nehru Nagar", "Civic Centre", "Supela", "Smriti Nagar", "Durg"],
    tagline: "Delivering authentic Agra sweets to Steel City Bhilai & Durg residences.",
    rating: "4.8★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha bhilai", "agra petha nehru nagar bhilai", "order petha civic centre", "sweets delivery durg bhilai"]
  },
  {
    name: "Bilaspur",
    slug: "bilaspur",
    state: "Chhattisgarh",
    region: "Central",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Vyapar Vihar", "Rajendra Nagar", "Civil Lines", "Torwa", "Mangla", "Nehru Nagar"],
    tagline: "Fresh sealed Agra petha boxes express dispatched to Bilaspur.",
    rating: "4.8★",
    ordersCount: "2,900+ Orders",
    keywords: ["buy petha bilaspur", "agra petha in bilaspur", "order sweets vyapar vihar bilaspur"]
  },

  // ==========================================
  // EAST & NORTH EAST INDIA
  // ==========================================
  {
    name: "Kolkata",
    slug: "kolkata",
    state: "West Bengal",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "80+ PIN Codes",
    popularAreas: ["Salt Lake", "Park Street", "Ballygunge", "New Town", "Alipore", "Howrah", "Dum Dum", "Gariahat", "Behala"],
    tagline: "For true sweet connoisseurs: pure Agra petha delivered right to your doorstep in Kolkata.",
    rating: "4.9★",
    ordersCount: "9,600+ Orders",
    keywords: ["buy petha kolkata", "agra petha delivery salt lake", "order petha online park street", "agra petha shop in kolkata", "best petha ballygunge"]
  },
  {
    name: "Howrah",
    slug: "howrah",
    state: "West Bengal",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["Shibpur", "Bally", "Salkia", "Mandirtala", "Liluah", "Santragachi", "Kadamtala"],
    tagline: "Daily air dispatched sweet boxes delivered directly to homes across Howrah.",
    rating: "4.8★",
    ordersCount: "3,800+ Orders",
    keywords: ["buy petha howrah", "agra petha shibpur howrah", "order sweets online howrah"]
  },
  {
    name: "Siliguri",
    slug: "siliguri",
    state: "West Bengal",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Sevoke Road", "Matigara", "Pradhan Nagar", "Hakim Para", "College Para", "Khalpara"],
    tagline: "Gateway to North East: air-shipped authentic Agra petha delivered to Siliguri.",
    rating: "4.9★",
    ordersCount: "4,100+ Orders",
    keywords: ["buy petha siliguri", "agra petha sevoke road siliguri", "order sweets matigara siliguri"]
  },
  {
    name: "Durgapur",
    slug: "durgapur",
    state: "West Bengal",
    region: "East",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["City Centre", "Benachity", "Bidhannagar", "Steel Township", "Fuljhor"],
    tagline: "Fresh vacuum-packed Agra petha & spicy Dalmoth delivered to Durgapur.",
    rating: "4.8★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha durgapur", "agra petha city centre durgapur", "order sweets benachity"]
  },
  {
    name: "Asansol",
    slug: "asansol",
    state: "West Bengal",
    region: "East",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Ushagram", "Burnpur", "Kalyanpur", "Court Area", "SB Gorai Road"],
    tagline: "Authentic royal Agra sweets express couriered to Asansol.",
    rating: "4.8★",
    ordersCount: "2,800+ Orders",
    keywords: ["buy petha asansol", "agra petha in asansol", "order sweets burnpur asansol"]
  },
  {
    name: "Bardhaman (Burdwan)",
    slug: "bardhaman",
    state: "West Bengal",
    region: "East",
    deliveryTime: "24–48 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Curzon Gate", "Golapbag", "Shaktigarh", "Khosbagan", "Badamtala"],
    tagline: "Sweet lovers paradise: authentic Agra petha delivered to Bardhaman.",
    rating: "4.8★",
    ordersCount: "2,300+ Orders",
    keywords: ["buy petha bardhaman", "agra petha burdwan", "order sweets online burdwan"]
  },
  {
    name: "Patna",
    slug: "patna",
    state: "Bihar",
    region: "East",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "55+ PIN Codes",
    popularAreas: ["Boring Road", "Kankarbagh", "Bailey Road", "Patliputra", "Rajendra Nagar", "Anisabad", "Danapur", "Fraser Road"],
    tagline: "Direct overnight express delivery of fresh GI-heritage Agra petha to Patna.",
    rating: "4.9★",
    ordersCount: "8,900+ Orders",
    keywords: ["buy petha patna", "agra petha boring road patna", "order petha online kankarbagh", "petha delivery bailey road patna", "best petha shop patna"]
  },
  {
    name: "Gaya",
    slug: "gaya",
    state: "Bihar",
    region: "East",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Bodh Gaya", "Civil Lines", "Rampur", "AP Colony", "Gaya Cantt", "Chandauti"],
    tagline: "Sacred city delivery of 100% pure vegetarian authentic Agra sweets to Gaya & Bodh Gaya.",
    rating: "4.9★",
    ordersCount: "4,200+ Orders",
    keywords: ["buy petha gaya", "agra petha bodh gaya", "order petha ap colony gaya", "petha delivery civil lines gaya"]
  },
  {
    name: "Bhagalpur",
    slug: "bhagalpur",
    state: "Bihar",
    region: "East",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Adampur", "Tilka Manjhi", "Zero Mile", "Khanjarpur", "Naya Bazaar", "Aliganj"],
    tagline: "Delivering sweet royalty from Agra to the Silk City Bhagalpur.",
    rating: "4.8★",
    ordersCount: "3,400+ Orders",
    keywords: ["buy petha bhagalpur", "agra petha tilka manjhi", "order petha online bhagalpur"]
  },
  {
    name: "Muzaffarpur",
    slug: "muzaffarpur",
    state: "Bihar",
    region: "East",
    deliveryTime: "24 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Mithanpura", "Brahmpura", "Kalambagh Road", "Juran Chhapra", "Aghoria Bazaar", "Motijheel"],
    tagline: "Fast courier dispatch of freshly vacuum-packed Agra petha to Muzaffarpur.",
    rating: "4.8★",
    ordersCount: "4,100+ Orders",
    keywords: ["buy petha muzaffarpur", "agra petha mithanpura", "order petha juran chhapra", "sweets delivery muzaffarpur"]
  },
  {
    name: "Darbhanga",
    slug: "darbhanga",
    state: "Bihar",
    region: "East",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Laheriasarai", "Tower Chowk", "Donar", "Benta", "Allalpatti", "Kathalbari"],
    tagline: "Authentic Agra sweets & savory Dalmoth delivered to the heart of Mithilanchal.",
    rating: "4.8★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha darbhanga", "agra petha laheriasarai", "order sweets online darbhanga"]
  },
  {
    name: "Purnia",
    slug: "purnia",
    state: "Bihar",
    region: "East",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Line Bazaar", "Bhatta Bazaar", "Madhubani", "Khuskibagh", "Gulabbagh"],
    tagline: "Fresh traditional Agra sweets dispatched daily to Purnia.",
    rating: "4.8★",
    ordersCount: "2,600+ Orders",
    keywords: ["buy petha purnia", "agra petha line bazaar purnia", "order sweets purnia"]
  },
  {
    name: "Ranchi",
    slug: "ranchi",
    state: "Jharkhand",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["Harmu", "Kanke Road", "Lalpur", "Doranda", "Hinoo", "Bariatu", "Morabadi", "Ashok Nagar"],
    tagline: "Direct air-shipped authentic Agra petha delivered fresh across Ranchi.",
    rating: "4.9★",
    ordersCount: "5,700+ Orders",
    keywords: ["buy petha ranchi", "agra petha kanke road ranchi", "order petha online lalpur", "petha delivery harmu ranchi"]
  },
  {
    name: "Jamshedpur (Tatanagar)",
    slug: "jamshedpur",
    state: "Jharkhand",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["Bistupur", "Sakchi", "Kadma", "Sonari", "Telco Colony", "Golmuri", "Baridih", "CH Area"],
    tagline: "Delivering sweet excellence to Steel City Jamshedpur with guaranteed freshness.",
    rating: "4.9★",
    ordersCount: "5,200+ Orders",
    keywords: ["buy petha jamshedpur", "agra petha bistupur tatanagar", "order petha sakchi kadma", "petha delivery sonari jamshedpur"]
  },
  {
    name: "Dhanbad",
    slug: "dhanbad",
    state: "Jharkhand",
    region: "East",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "30+ PIN Codes",
    popularAreas: ["Bank More", "Saraidhela", "Hirapur", "Koyla Nagar", "Bartand", "Dhansar"],
    tagline: "Freshly packed Agra petha & spicy Dalmoth delivered to Coal Capital Dhanbad.",
    rating: "4.8★",
    ordersCount: "3,900+ Orders",
    keywords: ["buy petha dhanbad", "agra petha bank more dhanbad", "order petha saraidhela", "sweets delivery dhanbad"]
  },
  {
    name: "Bokaro Steel City",
    slug: "bokaro",
    state: "Jharkhand",
    region: "East",
    deliveryTime: "24–36 Hours Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Sector 4", "Sector 1", "Chas", "Co-operative Colony", "Sector 9", "City Centre"],
    tagline: "Delivering authentic Agra sweets across Bokaro Steel City sectors & Chas.",
    rating: "4.8★",
    ordersCount: "3,300+ Orders",
    keywords: ["buy petha bokaro", "agra petha sector 4 bokaro", "order petha chas", "sweets delivery bokaro"]
  },
  {
    name: "Bhubaneswar",
    slug: "bhubaneswar",
    state: "Odisha",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "45+ PIN Codes",
    popularAreas: ["Saheed Nagar", "Patia", "Nayapalli", "Jayadev Vihar", "Chandrasekharpur", "Khandagiri", "Old Town", "Infocity"],
    tagline: "Air-freighted authentic Agra sweets delivered directly to the Temple City Bhubaneswar.",
    rating: "4.9★",
    ordersCount: "5,800+ Orders",
    keywords: ["buy petha bhubaneswar", "agra petha patia bhubaneswar", "order petha saheed nagar", "petha delivery chandrasekharpur"]
  },
  {
    name: "Cuttack",
    slug: "cuttack",
    state: "Odisha",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "35+ PIN Codes",
    popularAreas: ["CDA Sector 6-10", "Badambadi", "Link Road", "Choudhury Bazaar", "Madhupatna", "Bidanasi"],
    tagline: "Freshly sealed traditional Agra petha boxes delivered to Silver City Cuttack.",
    rating: "4.8★",
    ordersCount: "3,700+ Orders",
    keywords: ["buy petha cuttack", "agra petha cda cuttack", "order petha badambadi", "sweets delivery cuttack"]
  },
  {
    name: "Rourkela",
    slug: "rourkela",
    state: "Odisha",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Civil Township", "Sector 5", "Sector 19", "Koel Nagar", "Udit Nagar", "Panposh", "NIT Campus"],
    tagline: "Authentic Agra petha & spicy Dalmoth delivered to Rourkela & NIT students.",
    rating: "4.8★",
    ordersCount: "2,900+ Orders",
    keywords: ["buy petha rourkela", "agra petha civil township rourkela", "order petha nit rourkela"]
  },
  {
    name: "Berhampur (Brahmapur)",
    slug: "berhampur",
    state: "Odisha",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "25+ PIN Codes",
    popularAreas: ["Gandhi Nagar", "Gosani Nuagaon", "Bhavanagar", "Engineering School Road", "Kamapalli"],
    tagline: "Pure authentic Agra sweets delivered to Silk City Berhampur.",
    rating: "4.8★",
    ordersCount: "2,400+ Orders",
    keywords: ["buy petha berhampur", "agra petha brahmapur", "order sweets online berhampur"]
  },
  {
    name: "Puri",
    slug: "puri",
    state: "Odisha",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Grand Road", "VIP Road", "Sea Beach", "Chakratirtha Road", "Baliapanda", "Talabania"],
    tagline: "100% pure vegetarian sacred sweet boxes delivered to holy Dham Puri.",
    rating: "4.9★",
    ordersCount: "3,100+ Orders",
    keywords: ["buy petha puri", "agra petha grand road puri", "order sweets online puri", "petha delivery puri odisha"]
  },
  {
    name: "Guwahati",
    slug: "guwahati",
    state: "Assam",
    region: "East",
    deliveryTime: "24–48 Hours Air Express",
    pinCodesCount: "40+ PIN Codes",
    popularAreas: ["GS Road", "Zoo Road", "Ganeshguri", "Paltan Bazaar", "Six Mile", "Beltola", "Chandmari", "Jalukbari"],
    tagline: "Air-cargo expressed directly from Agra to the Gateway of North East Guwahati.",
    rating: "4.9★",
    ordersCount: "5,100+ Orders",
    keywords: ["buy petha guwahati", "agra petha gs road guwahati", "order petha online ganeshguri", "petha delivery beltola guwahati"]
  },
  {
    name: "Silchar",
    slug: "silchar",
    state: "Assam",
    region: "East",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Tarapur", "Rangirkhari", "Ambicapatty", "Hospital Road", "Meherpur", "NIT Silchar"],
    tagline: "Freshly sealed sweet boxes air-shipped to Barak Valley hub Silchar.",
    rating: "4.8★",
    ordersCount: "2,100+ Orders",
    keywords: ["buy petha silchar", "agra petha in silchar", "order sweets nit silchar"]
  },
  {
    name: "Dibrugarh",
    slug: "dibrugarh",
    state: "Assam",
    region: "East",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Graham Bazar", "Jalan Nagar", "Amolapatty", "Chowkidinghee", "Mancotta Road"],
    tagline: "Delivering sweet North Indian delicacies to the Tea City of India Dibrugarh.",
    rating: "4.8★",
    ordersCount: "1,900+ Orders",
    keywords: ["buy petha dibrugarh", "agra petha in dibrugarh", "order sweets online dibrugarh"]
  },
  {
    name: "Agartala",
    slug: "agartala",
    state: "Tripura",
    region: "East",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Banamalipur", "Radhanagar", "Akhaura Road", "Kunjaban", "Indranagar", "Dhaleswar"],
    tagline: "Air-freighted vacuum-fresh Agra petha delivered to Agartala.",
    rating: "4.8★",
    ordersCount: "1,800+ Orders",
    keywords: ["buy petha agartala", "agra petha in agartala", "order sweets online tripura"]
  },
  {
    name: "Shillong",
    slug: "shillong",
    state: "Meghalaya",
    region: "East",
    deliveryTime: "36–48 Hours Air Express",
    pinCodesCount: "20+ PIN Codes",
    popularAreas: ["Police Bazar", "Laitumkhrah", "Labal", "Mawlai", "Risa Colony", "Nongthymmai"],
    tagline: "Delivering sweet warmth to Scotland of the East Shillong with air freshness.",
    rating: "4.9★",
    ordersCount: "2,200+ Orders",
    keywords: ["buy petha shillong", "agra petha police bazar shillong", "order sweets laitumkhrah", "petha delivery shillong"]
  }
]
